USE [master]
GO
/****** Object:  Database [BD_Espacial]    Script Date: 22/04/2022 15:53:31 ******/
CREATE DATABASE [BD_Espacial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Espacial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BD_Espacial.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Espacial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BD_Espacial_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BD_Espacial] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Espacial].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BD_Espacial] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_Espacial] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_Espacial] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_Espacial] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_Espacial] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_Espacial] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BD_Espacial] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_Espacial] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_Espacial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_Espacial] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_Espacial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_Espacial] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_Espacial] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_Espacial] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_Espacial] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BD_Espacial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_Espacial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_Espacial] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BD_Espacial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BD_Espacial] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_Espacial] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_Espacial] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BD_Espacial] SET RECOVERY FULL 
GO
ALTER DATABASE [BD_Espacial] SET  MULTI_USER 
GO
ALTER DATABASE [BD_Espacial] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_Espacial] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BD_Espacial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BD_Espacial] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BD_Espacial] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BD_Espacial] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BD_Espacial', N'ON'
GO
ALTER DATABASE [BD_Espacial] SET QUERY_STORE = OFF
GO
USE [BD_Espacial]
GO
/****** Object:  Table [dbo].[Calle]    Script Date: 22/04/2022 15:53:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Table [dbo].[TipoProducto](
	[idTipoProducto] [int] NOT NULL,
	[nombre] [varchar](30) NOT NULL,
 CONSTRAINT [PK_idTipoProducto] PRIMARY KEY CLUSTERED 
(
	[idTipoProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Calle](
	[idCalle] [int] NOT NULL,
	[distancia] [geography] NOT NULL,
 CONSTRAINT [PK_Calle] PRIMARY KEY CLUSTERED 
(
	[idCalle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Casa]    Script Date: 22/04/2022 15:53:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Casa](
	[idCasa] [int] NOT NULL,
	[nombre] [varchar](10) NOT NULL,
	[ubicacion] [geography] NOT NULL,
	[idCalle] [int] NOT NULL,
 CONSTRAINT [PK_Casa] PRIMARY KEY CLUSTERED 
(
	[idCasa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Comercio]    Script Date: 22/04/2022 15:53:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comercio](
	[idComercio] [int] NOT NULL,
	[nombre] [varchar](10) NOT NULL,
	[idTipo] [int] NOT NULL,
	[ubicacion] [geography] NOT NULL,
	[idCalle] [int] NOT NULL,
 CONSTRAINT [PK_Comercio] PRIMARY KEY CLUSTERED 
(
	[idComercio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 22/04/2022 15:53:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[idProducto] [int] NOT NULL,
	[idComercio] [int] NOT NULL,
	[nombre] [varchar](15) NOT NULL,
	[peso] [varchar](10) NOT NULL,
	[descripcion] [varchar](20) NOT NULL,
	[precio] [float] NOT NULL,
	[idTipoProducto] [int] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[idProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoComercio]    Script Date: 22/04/2022 15:53:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoComercio](
	[idTipoComercio] [int] NOT NULL,
	[nombre] [varchar](10) NOT NULL,
	[horaabierto] [time](7) NOT NULL,
	[horacerrado] [time](7) NOT NULL,
 CONSTRAINT [PK_TipoComercio] PRIMARY KEY CLUSTERED 
(
	[idTipoComercio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Casa]  WITH CHECK ADD  CONSTRAINT [FK_Casa_Calle] FOREIGN KEY([idCalle])
REFERENCES [dbo].[Calle] ([idCalle])
GO
ALTER TABLE [dbo].[Casa] CHECK CONSTRAINT [FK_Casa_Calle]
GO
ALTER TABLE [dbo].[Comercio]  WITH CHECK ADD  CONSTRAINT [FK_Comercio_Calle] FOREIGN KEY([idCalle])
REFERENCES [dbo].[Calle] ([idCalle])
GO
ALTER TABLE [dbo].[Comercio] CHECK CONSTRAINT [FK_Comercio_Calle]
GO
ALTER TABLE [dbo].[Comercio]  WITH CHECK ADD  CONSTRAINT [FK_Comercio_TipoComercio] FOREIGN KEY([idTipo])
REFERENCES [dbo].[TipoComercio] ([idTipoComercio])
GO
ALTER TABLE [dbo].[Comercio] CHECK CONSTRAINT [FK_Comercio_TipoComercio]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_Comercio] FOREIGN KEY([idComercio])
REFERENCES [dbo].[Comercio] ([idComercio])
GO
Alter Table [dbo].[Producto] WITH CHECK ADD  CONSTRAINT [FK_idTipoProducto] FOREIGN KEY([idTipoProducto])
References [dbo].[TipoProducto] ([idTipoProducto])
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Comercio]
GO
USE [master]
GO
ALTER DATABASE [BD_Espacial] SET  READ_WRITE 
GO
